USE [master]
GO

/****** Object:  Database [TureAgenstvo]    Script Date: 22.11.2022 14:54:25 ******/
CREATE DATABASE [TureAgenstvo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TureAgenstvo', FILENAME = N'D:\Новая папка\MSSQL15.SQLEXPRESS\MSSQL\DATA\TureAgenstvo.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TureAgenstvo_log', FILENAME = N'D:\Новая папка\MSSQL15.SQLEXPRESS\MSSQL\DATA\TureAgenstvo_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TureAgenstvo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TureAgenstvo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TureAgenstvo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TureAgenstvo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TureAgenstvo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TureAgenstvo] SET ARITHABORT OFF 
GO

ALTER DATABASE [TureAgenstvo] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TureAgenstvo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TureAgenstvo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TureAgenstvo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TureAgenstvo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TureAgenstvo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TureAgenstvo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TureAgenstvo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TureAgenstvo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TureAgenstvo] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TureAgenstvo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TureAgenstvo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TureAgenstvo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TureAgenstvo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TureAgenstvo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TureAgenstvo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TureAgenstvo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TureAgenstvo] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TureAgenstvo] SET  MULTI_USER 
GO

ALTER DATABASE [TureAgenstvo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TureAgenstvo] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TureAgenstvo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TureAgenstvo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TureAgenstvo] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TureAgenstvo] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TureAgenstvo] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TureAgenstvo] SET  READ_WRITE 
GO


