USE [master]
GO

/****** Object:  Database [Blagodat]    Script Date: 26.11.2022 20:44:57 ******/
CREATE DATABASE [Blagodat]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Blagodat', FILENAME = N'D:\Новая папка\MSSQL15.SQLEXPRESS\MSSQL\DATA\Blagodat.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Blagodat_log', FILENAME = N'D:\Новая папка\MSSQL15.SQLEXPRESS\MSSQL\DATA\Blagodat_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Blagodat].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Blagodat] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Blagodat] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Blagodat] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Blagodat] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Blagodat] SET ARITHABORT OFF 
GO

ALTER DATABASE [Blagodat] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Blagodat] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Blagodat] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Blagodat] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Blagodat] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Blagodat] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Blagodat] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Blagodat] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Blagodat] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Blagodat] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Blagodat] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Blagodat] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Blagodat] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Blagodat] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Blagodat] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Blagodat] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Blagodat] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Blagodat] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Blagodat] SET  MULTI_USER 
GO

ALTER DATABASE [Blagodat] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Blagodat] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Blagodat] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Blagodat] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Blagodat] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Blagodat] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Blagodat] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Blagodat] SET  READ_WRITE 
GO


